### ISSUE TITLE
sapnwrfc.dll not found

### ISSUE THREAD

**Issue by gerritlo** [mydoghasworms/nwrfc#9]
Hey at all,

I try to use the sdk and have downloaded sap rfcsdk on windows and extracted to D:\Programme\rfcsdk.

I've also installed the gem nwrfc and included shown in the example but I get th error:
`Could not open library 'sapnwrfc.dll': Das angegebene Modul wurde nicht gefunden.`

What can be the reason?

**Comment by mydoghasworms** [comment]
On Windows, the PATH environment variable must include the location of the RFC DLL, which would be in the \lib directory.

**Comment by veda123** [comment]
Hi,
I have installed  gems "sapnwrfc" and "nwrfc", followed all the steps . I have included the location of sapnwrfc.dll in the PATH environment variable. Unfortunately , I am getting "Could not open library 'sapnwrfc.dll': The specified module could not be found". Can you please let me know what am I missing?
